### ISSUE TITLE
what happens if we try to download (and later rerun) an ongoing CI run logs?

### ISSUE THREAD

**Issue by yarikoptic** [con/tinuous#135]
i.e. will we just get a partial result and then upon rerun skip that run completely?

**Comment by jwodder** [comment]
@yarikoptic Any actions that are still in progress are skipped when downloading, and the timestamp saved in the statefile will be before the earliest in-progress action, so on a subsequent run, the skipped action (if it's completed by then) will have its logs downloaded, and any actions after it that were downloaded previously will be skipped due to there already being logfiles saved locally.

**Comment by yarikoptic** [comment]
Great, thank you
